nodeLinker: node-modules

npmScopes:
  avada:
    npmAlwaysAuth: true
    npmAuthToken: OUujf6Frq8k2UbEfzZDK3QKYR0AmYmPZsYBA89LdnIk=
    npmRegistryServer: "https://registry.avada.io"
  shopify:
    npmRegistryServer: "https://registry2.avada.io"
