# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "656cb28c4da4be7d48ec137b95adaca0"
name = "simple-sale-pop"
handle = "simple-sale-pop-3"
application_url = "https://oils-must-tank-den.trycloudflare.com/auth/shopify"
embedded = true

[webhooks]
api_version = "2025-07"

[auth]
redirect_urls = ["https://oils-must-tank-den.trycloudflare.com/auth/shopify/callback", "https://oils-must-tank-den.trycloudflare.com/authSa/shopify/callback", "https://oils-must-tank-den.trycloudflare.com/auth/shopify/embed/callback", "https://oils-must-tank-den.trycloudflare.com/auth/shopify/embed/callback/updateScopes", "https://localhost:3000/auth/shopify/callback", "https://localhost:3000/authSa/shopify/callback", "https://localhost:3000/auth/shopify/embed/callback"]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
